completed css-two-column-layout
Wizzo1337/m1-1120-code-solutions pull request #19
Opened 2020-12-05 18:33 UTC by Wizzo1337

css two column layout | Thomas Willson

2020-12-05 22:10 UTC, uzair-ashraf requested changes

2020-12-05 22:10 UTC, uzair-ashraf commented on css-two-column-layout/styles.css
> +  flex-direction: column;
Does not work on not flex containers, you can remove this since block level elements by default sit ontop of each other

2020-12-09 05:13 UTC, uzair-ashraf approved these changes

2020-12-09 05:46 UTC, merged

2020-12-09 05:47 UTC, Wizzo1337 commented
![image](https://user-images.githubusercontent.com/71527908/101590294-fa300880-399e-11eb-8c99-da7d5763058e.png)