completed css-canvas-medical
Wizzo1337/m1-1120-code-solutions pull request #21
Opened 2020-12-09 20:44 UTC by Wizzo1337

![image](https://user-images.githubusercontent.com/71527908/101685153-41101380-3a1c-11eb-9d16-8712023648da.png)
![image](https://user-images.githubusercontent.com/71527908/101685188-4e2d0280-3a1c-11eb-84dc-7be9a8ef87ae.png)

2020-12-09 20:45 UTC, Wizzo1337 commented
those are 2 screenshots, didn't know how to scroll down while taking a screenshot

2020-12-10 18:45 UTC, uzair-ashraf requested changes

2020-12-10 18:45 UTC, uzair-ashraf commented on css-canvas-medical/styles.css
> +}
These do not need to be position absolute, they can be done properly with a flex container.

2020-12-10 18:45 UTC, uzair-ashraf commented on css-canvas-medical/styles.css
> +}
Same here

2020-12-10 18:45 UTC, uzair-ashraf commented on css-canvas-medical/styles.css
> +}
With some margin as well

2020-12-11 03:06 UTC, Wizzo1337 commented
![image](https://user-images.githubusercontent.com/71527908/101856718-bb26c200-3b1a-11eb-8c35-1270ef8db330.png)
![image](https://user-images.githubusercontent.com/71527908/101856736-c37efd00-3b1a-11eb-9201-d5bb8bb1c558.png)

2020-12-11 03:22 UTC, uzair-ashraf requested changes

2020-12-11 03:22 UTC, uzair-ashraf commented on css-canvas-medical/styles.css
> +}
This is not the appropriate use case for position relative.  Margin and padding to adjust movement, with a proper grid system layout will five you the output you are looking for.

2020-12-11 03:22 UTC, uzair-ashraf commented on css-canvas-medical/styles.css
> +}
same here, align content center if justify-content start with a flex container will remove the need for position relative.

2020-12-11 04:18 UTC, Wizzo1337 commented
![image](https://user-images.githubusercontent.com/71527908/101861382-c8e14500-3b24-11eb-8ddb-9fc2c4f5c0f2.png)
![image](https://user-images.githubusercontent.com/71527908/101861395-d26aad00-3b24-11eb-8825-b044bc6f924e.png)

2020-12-11 04:55 UTC, uzair-ashraf approved these changes

2020-12-11 05:13 UTC, merged