completed JS loops
Wizzo1337/m1-1120-code-solutions pull request #35
Opened 2021-01-02 20:13 UTC by Wizzo1337

![image](https://user-images.githubusercontent.com/71527908/103465798-e3f23f80-4cf3-11eb-8051-9cf9309fc916.png)

2021-01-05 23:28 UTC, uzair-ashraf requested changes

2021-01-05 23:28 UTC, uzair-ashraf commented on javascript-loops/main.js
> +}
For in loop implemented incorrectly.
Checkout your solution below.

2021-01-06 01:55 UTC, Wizzo1337 commented
![image](https://user-images.githubusercontent.com/71527908/103720016-40b55a80-4f7f-11eb-9a6a-deb2f8b579dc.png)

2021-01-13 03:38 UTC, uzair-ashraf approved these changes

2021-01-13 06:09 UTC, merged